### ISSUE TITLE
Length Flocculator?

### ISSUE THREAD

**Issue by tm545** [AguaClara/fluoride#13]
Could you confirm our length of flocculator, because on your flocculator values drive page shows two separate values for this length, one being 13.709m for 1mm/s and the other as 11.827m for the 3mm/s flocculator. Our flocculator was a 1.5mm/s so we're not sure which value is accurate or if the fluoride team had a flocculator with a length between these two values.
Thanks in advance.

**Comment by TanviNaidu** [comment]
You will need a different flocculator length, in between those two values. There is a place in the mathcad file to input sed tank upflow velocity (in your case, 1.5 mm/s). If you want help with mathcad while transitioning to python, let me know.

**Comment by TanviNaidu** [comment]
Hey team, 
3:30 on Friday doesn't work for me, but I am free in the morning on Friday till 11:15. 
What are your other meeting times?

**Comment by vxz3** [comment]
Monday, Tuesday, Thursday 4:30-6:30 & Wednesday 2-4

**Comment by vxz3** [comment]
Do you have any time to meet this week?

**Comment by TanviNaidu** [comment]
Yes, I can meet you on Wednesday at 2!

**Comment by vxz3** [comment]
Great! Thanks!

**Comment by pakpan** [comment]
Hi Tanvi,

Were you still planning on coming in to the lab to meet with us today?
