### ISSUE TITLE
Construct gravity powered fluoride removal system

### ISSUE THREAD

**Issue by DesireeJSausele** [AguaClara/fluoride#17]
First confirm that calculations of dimensions are correct and then create a to scale schematic. Collect the necessary materials and begin construction (may need to consult with Paul)

*note: if it is not feasible to build the system at our desk, then we will need to find an alternate location.

**Comment by vxz3** [comment]
Began constructing gravity powered reactor based off Fusion design. Built base this week and starting making the shelves by cutting 80/20 bars and PVC sheets. Slow and steady progress.

**Comment by vxz3** [comment]
Finished construction of base/support structures and beginning to attach nalgene bottles, buckets, flocculators, etc.

**Comment by vxz3** [comment]
Attached tubing and checked for leaks in the system, replacing the connections that were faulty.

**Comment by vxz3** [comment]
Tested the reactor and water does flow in the reactor and out through the effluent line.

**Comment by vxz3** [comment]
Replaced some connections that were leaking.

**Comment by vxz3** [comment]
Now that the gravity powered reactor is up and running, the summer team can start running tests!
