### ISSUE TITLE
standard calibration issues

### ISSUE THREAD

**Issue by tm545** [AguaClara/fluoride#18]
I have questions about your standard calibrations and the r^2 values associated, there seems to be no equations behind the r2 values, how did you get them and what column corresponds with what?

**Comment by vxz3** [comment]
There's a function in excel so you just select your x and y values.

**Comment by tm545** [comment]
![capture](https://user-images.githubusercontent.com/36340132/37542990-824140c6-2936-11e8-8134-25bc72e537b8.PNG)

**Comment by vxz3** [comment]
So those I probably did on another sheet and copied over later.

**Comment by tm545** [comment]
whats that third column for? does that mean you added ISA to those tap values?

**Comment by vxz3** [comment]
yup

**Comment by tm545** [comment]
thanks muffin
