### ISSUE TITLE
Information on float valves

### ISSUE THREAD

**Issue by tm545** [AguaClara/fluoride#24]
The fluoride team is going to be using float valves for their gravity power design, and we realized we aren't sure about how these work and how to implement them. Would you mind sharing your knowledge with us when is good for you.

**Comment by pakpan** [comment]
Hi Cynthia,
I sent an invite on google calendar for Thursday, 4/26 from 4:30 to 5:30. Let us know if this works for you! Thanks!

**Comment by FelixYuHengYang** [comment]
Hi. I'm available Tuesday and Thursdays 230-530 and Tuesdays 7-9.
