### ISSUE TITLE
fluoride probe short life

### ISSUE THREAD

**Issue by monroews** [AguaClara/fluoride#25]
Proposed steps

- Clean the probe with deionized water that has the pH lowered to 3 using HCl. This would clean any coagulant nanoparticles from the probe in case those nanoparticles are interfering with the measurements
- call the fluoride probe vender to see what cleaning steps they suggest
- See [Fluoride probe manual](https://assets.thermofisher.com/TFS-Assets/LSG/manuals/D15872~.pdf) for possible suggestions for measurements/care/cleaning
- investigate options at VWR. search for Fluoride electrode
- It looks like we will have to pay something between $600 and $1000. I am concerned that given how we use the probe that these expensive probes won't last any longer... So Ideally we figure out what is required to care for a probe so that it lasts longer!

**Comment by vxz3** [comment]
Ok, we'll try that and update you as we go!
