### ISSUE TITLE
Some thoughts for the summer

### ISSUE THREAD

**Issue by vxz3** [AguaClara/fluoride#33]
List of goals:

-Build new reactor (old reactor was (badly) welded together)
-Fix all leaks in gravity powered reactor
-Figure out a way to keep effluent line fixed at certain height
-Order new probe (BNC connector) with longer shelf life
-Verify adsorption model
-Run tests and measure effluent concentration to see if concentration is below 1.5 mg/L
-Calculate major loss due to friction for 1/4'' tubing and verify assumption that this headloss is negligible.

**Comment by pakpan** [comment]
A good idea would be to add some valves to the exits of the constant head tanks so that they can fill up from the reservoirs prior to beginning the experiment.
