### ISSUE TITLE
Changing pump speeds on ProCoDA

### ISSUE THREAD

**Issue by cheertsang** [AguaClara/fluoride#37]
Hi @WPennock @jillianwhiting @monroews  ! We were wondering if you could help us with ProCoDA. We are trying to change the pump speeds, but the pumps are not responding to the changes we make in ProCoDA. A couple things we tried:
- Changed the set points for pump speed.
- Checked that pumps are running on external input
- Checked that pump ID was correct
- Checked that pump ID and flow rate was selected in water pump set point
- Calibrated pumps
![capture](https://user-images.githubusercontent.com/35718077/41301908-25f01ea0-6e37-11e8-9a43-a18cf731ae6c.png)
![capture2](https://user-images.githubusercontent.com/35718077/41301909-2602c686-6e37-11e8-886e-326c9edb3af1.png)

Do you have any suggestions on what else we could try?
Thank you!

**Comment by jillianwhiting** [comment]
Cheer,
How far off is it? Like only one or two rpm or a lot. If it is very far off try another pump cable. If they are pretty close sometimes when the pump is off, it is still running at like 1 rpm and then if you hit the stop button when you run it via procoda again it will be right. Those are the two problems I know.

Jill

**Comment by cheertsang** [comment]
Hi Jillian: 
It is running at the same speed no matter what we change the pump speed set point to. Right now, it is running at 22 rpm. We set the pump speed set point to 1.013 mL/s, and at this rate, we calculated that the pump should be running at 76 rpm. We also tried inputting different pump speed values, but it didn't change the pump speed on the actual pump.

**Comment by jillianwhiting** [comment]
Cheer,

That sounds like an issue with either the pump cord or the pump itself. I would try to see what happens when you use a different cord or pump.

Jill

**Comment by ChingPangggg** [comment]
Hi Jillian.

We tried to change the pump cords but nothing really happened. Also, all three pumps we tried connected to ProCoDA, but none of them respond to the changes we made in ProCoDA. Should we switch out all three pumps?

**Comment by cheertsang** [comment]
@pakpan @tm545 @DesireeJSausele Did you guys have this issue with the pumps last semester?

**Comment by monroews** [comment]
Need more details.
DO the pumps turn on?
You are sending them the command to run at full speed. Are they running at full speed?

**Comment by monroews** [comment]
When you changed the inputs, what did the target pump speed change to? In the image below the target pump speed is 1. Does the pump run at full speed with this setting?
![image](https://user-images.githubusercontent.com/28540907/41363938-3331628c-6f03-11e8-89ce-a9a28a41d0b5.png)

**Comment by cheertsang** [comment]
We tried putting a pressure sensor, and the ports for the sensors don't work either, so we think the problem is the box for the ports.

**Comment by monroews** [comment]
Is your PRoCoDA box plugged in to power?
Does your Fluoride sensor work?
Try a different workstation and see if you can control a pump (WITHOUT CHANGING ANYTHING) at that station (perhaps use 2 stage coag station).

Once you have a working station then swap parts to figure out what isn't working at the fluoride station.

**Comment by monroews** [comment]
Check to see if the PRoCoDA box is plugged in to power.

**Comment by cheertsang** [comment]
Unplugging and plugging it back in again seemed to solve the issue of the ProCoDA box - now our fluoride sensor is working. The only issue we have now is changing pump speeds...we are going to try using our pumps with the 2 stage station to see if that works.

**Comment by monroews** [comment]
The power supply on the ProCoDA box turns off if it is overloaded. THis can happen if someone plugs a valve into a sensor port. I believe you reset the power supply by unplugging the power and plugging the power back in again. I'm assuming it was the power that you unplugged....

**Comment by ChingPangggg** [comment]
Pump speeds were fixed by changing set points and outputs in ProCoDA.
