### ISSUE TITLE
Gravity Powered System Adjustment

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/fluoride#39]
Tasks:
1. Measure actual flow rate of the gravity powered system by timing water exiting the effluent
2. Check if the flow rate is at 0.76 mL/s
3. Adjust the height if the flow rate does not agree with the upflow velocity of 1.5 mm/s

**Comment by ChingPangggg** [comment]
06/15/2018
First test of flow rate (effluent): 0.4762 ml/s
--> (need to adjust the height to reach 0.76 ml/s)
Shortened the tubing between the T-connection and the fluoride tank

**Comment by ChingPangggg** [comment]
Added Bars to the system to make sure the filled constant head tank and fluoride stock tank are stable.

**Comment by cheertsang** [comment]
Set up gravity powered system, fixed all leaks and structural instabilities. 
Adjusted height of fluoride constant head tank and height of sedimentation tube to achieve upflow velocity of 1.5 mm/s.
