### ISSUE TITLE
PACl Order

### ISSUE THREAD

**Issue by IanCullings** [AguaClara/fluoride#42]
Hey guys, once you have an idea of how much PACl you'll be using each week (at the concentration in the lab), could you let me know so I can order more for the rest of the summer?

**Comment by cheertsang** [comment]
Hi Ian:

I am estimating that we will need about 200 mL of coagulant per week (and this is a high estimate).

**Comment by cheertsang** [comment]
@IanCullings Is this a reasonable amount of coagulant that we can use each week?

**Comment by IanCullings** [comment]
@cheertsang that is totally fine, I'll put in the order early next week.
