### ISSUE TITLE
Running Blue Dye Experiment on Gravity-Powered System

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/fluoride#43]
Using blue dye as fluoride and 12.5 mg/L PACl as coagulant--> No floc is observed
Using blue dye as fluoride and 639 mg/L PACl as coagulant (10mL of PACl/ 1L of DI water)--> floc is observed

**Comment by cheertsang** [comment]
Set up gravity powered experiment. Used blue dye to model fluoride. 
![img_20180619_105524161](https://user-images.githubusercontent.com/35718077/41605788-28679054-73b0-11e8-9a74-c112e6a29efa.jpg)

**Comment by cheertsang** [comment]
Observed flocs in [flocculator](https://drive.google.com/file/d/1pqRy6iY53kdztgW_0-1btEq0jRNrlrRx/view?usp=sharing)

**Comment by cheertsang** [comment]
flow rate through plant: 0.74 mL/s 
flow rate through waste: 0.0014 mL/s
