### ISSUE TITLE
6/29 Fluoride 3 mg/L

### ISSUE THREAD

**Issue by cheertsang** [AguaClara/fluoride#51]
**PACl 10 mg/L**

Ran experiment for 3.5 hours.
Took 2 samples. 
No observed flocs in sedimentation tube.
Data and calibration curve found [here](https://docs.google.com/spreadsheets/d/1Qdzn8rtu0ubeyHFeoxpHNJPTBkcbFvO21DLpOUB-Flc/edit#gid=974397563).

**Comment by cheertsang** [comment]
**PACl 15 mg/L**

Ran experiment for 6 hours. 
Took 5 samples. 
Flocs congealed into a gel in the sedimentation tube. Upflow velocity may be too slow. 
Data and calibration curve found [here](https://docs.google.com/spreadsheets/d/1Qdzn8rtu0ubeyHFeoxpHNJPTBkcbFvO21DLpOUB-Flc/edit#gid=974397563).

**Comment by cheertsang** [comment]
**PACl 20 mg/L**
![img_20180701_160632834](https://user-images.githubusercontent.com/35718077/42138818-822d3c6a-7d51-11e8-92c4-8ee87df60e40.jpg)

Ran experiment for 6 hours.

**Comment by ChingPangggg** [comment]
**PACl 30 mg/L**
7/2/2018

**Comment by ChingPangggg** [comment]
**PACl 40 mg/L**
7/3/2018

**Comment by cheertsang** [comment]
PACl started to make a difference at 20 mg/L for 3 mg/L influent fluoride.
