### ISSUE TITLE
Gravity Powered System Supplies

### ISSUE THREAD

**Issue by cheertsang** [AguaClara/fluoride#53]
Hi @monroews !

We are beginning to modify our gravity powered system to make it easier to adjust the heights of the constant head tanks. We are planning to order sliding sleeve-bearing carriages. 

This would require:

1. [Side-Mount Bearing](https://www1.mcmaster.com/#47065t779/=1dlj45f)
2. [Side Bearing Pad](https://www1.mcmaster.com/#47065T774)
3. [Top Bearing Pad](https://www.mcmaster.com/#47065T774)
4. [Hand brake](https://www.mcmaster.com/#60585K31)

We would need 5 of each of these. 

The total cost for this purchase would be: $268.96. 

Would this be a reasonable purchase? 

Thank you!

**Comment by monroews** [comment]
These look excellent. If I recall correctly you need the ability to adjust the height of the exit tubing that leaves the sedimentation tank where it discharges to the atmosphere. You also need to be able to adjust the height of the coagulant stock tank. Does that match what you were thinking?
