### ISSUE TITLE
Influent ad Effluent measurement

### ISSUE THREAD

**Issue by ChingPangggg** [AguaClara/fluoride#56]
Air bubbles will appear in the system (in the reactor) since we have to disconnect the tubing to take the influent sample. We think that this will have an effect in formation of floc blanket in the reactor. Therefore, we are thinking about  installing a t-connection and a valve after the fluoride is added and before the PACl enters the system.

**Comment by cheertsang** [comment]
5 rpm = The PACl flow rate is: 0.001583 milliliter / second
10 rpm = The PACl flow rate is: 0.003167 milliliter / second
20 rpm = The PACl flow rate is: 0.006333 milliliter / second
30 rpm = The PACl flow rate is: 0.0095 milliliter / second
40 rpm = The PACl flow rate is: 0.01267 milliliter / second

**Comment by ChingPangggg** [comment]
Valve was added after adding fluoride and before adding coagulant in the system.
![valve](https://raw.githubusercontent.com/AguaClara/fluoride/master/Summer%202018%20fluoride%20report/influent_valve.jpg)
