### ISSUE TITLE
Determine optimal upflow velocity

### ISSUE THREAD

**Issue by DesireeJSausele** [AguaClara/fluoride#6]
Run experiments varying the upflow velocity through the sedimentation tube and analyze results to measure removal efficiency and obtain an optimal upflow velocity

**Comment by vxz3** [comment]
Optimal velocity determined to be 1.5 mm/s. 1 mm/s is too slow and causes clogging in bottom of reactor and 2 mm/s is too fast and pushing flocs out of effluent line.
